#!/bin/bash

#Verificando a quantidade de argumentos
if [ $# -le 2 ]; then
	echo "Erro! Não foram fornecidos os dois argumentos."
	exit 1
fi

#Trecho de codigo totalmente descartavel
arg1=$1
arg2=$2

#Impressao dos argumentos
echo "O primeiro argumento é: $arg1"
echo "O segundo argumento é: $arg2"
